blogger_blog_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

blogger_blog_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

blogger_blog_contact:
    path: /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods: GET|POST

blogger_blog_show:
    path: /show/{id}/{slug}
    defaults: { _controller: "BloggerBlogBundle:Blog:show" }
    requirements:
        methods: GET
        id: \d+

blogger_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+